name: fushi_asr_workspace
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

workspace:
  - packages/asr
  - packages/asr_align
  - packages/asr_cli
  - packages/asr_core
  - packages/asr_onnx_ffi
  - packages/asr_subtitles
  - packages/asr_server
