// Compile Tailwind and embed all UI assets in Dart for offline/AOT deployment.
import { readFileSync, writeFileSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { build } from 'esbuild';
const root = dirname(fileURLToPath(import.meta.url));
const scratch = mkdtempSync(join(tmpdir(), 'fushi-tailwind-'));
try {
  const cssPath = join(scratch, 'styles.css');
  const cli = join(root, 'node_modules/@tailwindcss/cli/dist/index.mjs');
  const result = spawnSync(process.execPath, [cli, '-i', 'styles.css', '-o', cssPath, '--minify'], { cwd: root, stdio: 'inherit' });
  if (result.error) throw result.error;
  if (result.status !== 0) throw new Error('Tailwind build failed');
  const bundle = await build({
    absWorkingDir: root, entryPoints: ['src/main.tsx'], bundle: true,
    write: false, outdir: scratch, format: 'iife', minify: true,
    charset: 'utf8', target: ['es2022'], jsx: 'automatic',
    define: { 'process.env.NODE_ENV': '"production"' },
    // The logo has to travel inside the single HTML file: no second request is allowed.
    loader: { '.png': 'dataurl' },
    plugins: [{ name: 'css-is-compiled-by-tailwind', setup(b) {
      b.onLoad({ filter: /\.css$/ }, () => ({ contents: '', loader: 'css' }));
    } }],
  });
  const js = bundle.outputFiles.find(f => f.path.endsWith('.js')).text;
  const html = readFileSync(join(root, 'index.html'), 'utf8')
    .replace('</head>', () => '<style>' + readFileSync(cssPath, 'utf8') + '</style></head>')
    .replace('<script type="module" src="/src/main.tsx"></script>', () => '<script>' + js.replace(/<\/script/gi, '<\\/script') + '</script>');
  if (html.includes("'''")) throw new Error('Dart raw-string delimiter in UI source');
  writeFileSync(join(root, '../lib/src/web_ui.g.dart'), "// GENERATED by web/build.mjs. Edit web/ sources, then npm run build.\nconst webUiDocument = r'''" + html + "''';\n");
} finally {
  rmSync(scratch, { recursive: true, force: true });
}
